/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hib;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author koren
 */
public class ConsultarEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarEmpleados
     */
    public ConsultarEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFapellido = new javax.swing.JTextField();
        TFnumero = new javax.swing.JTextField();
        TFoficio = new javax.swing.JTextField();
        TFsalario = new javax.swing.JTextField();
        TFdepartamento = new javax.swing.JTextField();
        BTNconsulta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BTNsiguiente = new javax.swing.JButton();
        BTNanterior = new javax.swing.JButton();
        BTNultimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("num de empleado");

        jLabel2.setText("apellido");

        jLabel3.setText("oficio");

        jLabel4.setText("departamento");

        jLabel5.setText("salario");

        TFapellido.setFocusable(false);

        TFoficio.setFocusable(false);

        TFsalario.setFocusable(false);

        TFdepartamento.setFocusable(false);

        BTNconsulta.setText("Ejecutar consulta");
        BTNconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNconsultaActionPerformed(evt);
            }
        });

        jButton2.setText("Primer Reg");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BTNsiguiente.setText("Siguiente");
        BTNsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsiguienteActionPerformed(evt);
            }
        });

        BTNanterior.setText("Anterior");
        BTNanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNanteriorActionPerformed(evt);
            }
        });

        BTNultimo.setText("Ultimo Reg");
        BTNultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNultimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(BTNconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNsiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNanterior))
                            .addComponent(TFsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFoficio, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(BTNultimo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNconsulta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFoficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(BTNsiguiente)
                    .addComponent(BTNanterior)
                    .addComponent(BTNultimo))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNconsultaActionPerformed
        // TODO add your handling code here:
        // •	El botón Ejecutar consulta y Primer Reg deben mostrar el primer empleado (el que tiene menor número de empleado). Si no hay empleados visualizar mensaje indicándolo. 

        SessionFactory sesion = HibernateUtil.getSesionFactory();
        Session session = sesion.openSession();

         //Posicion que tiene
        int codEmpl = Integer.valueOf(TFnumero.getText().toString());

        Query q2 = session.createQuery("from Empleados");
        q2.setFetchSize(10);
        Iterator iter2 = q2.iterate();
        // System.out.println(min);
        while(iter2.hasNext()){
             
            Empleados emple = (Empleados) iter2.next();
            int EMPc = emple.getEmpNo();
             if(EMPc==codEmpl){
                 TFnumero.setText(emple.getEmpNo()+"");
                 TFapellido.setText(emple.getApellido()+"");
                 TFoficio.setText(emple.getOficio()+"");
                 TFdepartamento.setText(emple.getDepartamentos().getDnombre()+"");
                 TFsalario.setText(emple.getSalario()+"");
                // System.out.println(res);
             }  
       }
       
        
        
         
        session.close();
    }//GEN-LAST:event_BTNconsultaActionPerformed

    private void BTNsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsiguienteActionPerformed
        //•	El botón Siguiente muestra el siguiente empleado al que se está visualizando en este momento. Si se pulsa y estamos ante el último empleado se debe visualizar un mensaje indicándolo (por ejemplo: “No hay más empleados”). 
//•	El botón Siguiente muestra el siguiente empleado al que se está visualizando en este momento. Si se pulsa y estamos ante el último empleado se debe visualizar un mensaje indicándolo (por ejemplo: “No hay más empleados”). 

        SessionFactory sesion = HibernateUtil.getSesionFactory();
        Session session = sesion.openSession();

        Query q5 = session.createQuery("from Empleados");

        q5.setFetchSize(10);
        Iterator iter5 = q5.iterate();

        ArrayList<Integer> listaEmp = new ArrayList<Integer>();

        while (iter5.hasNext()) {
            Empleados emple = (Empleados) iter5.next();
            int EMPc = emple.getEmpNo();
            listaEmp.add(EMPc);
        }

        //Posicion que tiene
        int codEmpl = Integer.valueOf(TFnumero.getText().toString());
        int position = 0;

        //Ultima posicion
        int ultimo = listaEmp.get(listaEmp.size() - 1);
        System.out.println("El ultimo numero empleado es: "+ultimo);

        
        if (codEmpl != ultimo) {
            for (int i = 0; i < listaEmp.size(); i++) {
                if (listaEmp.get(i) == codEmpl) {
                    position = listaEmp.get(i + 1);
                }
            }
        }

        Query q6 = session.createQuery("from Empleados");
        q6.setFetchSize(10);
        Iterator iter6 = q6.iterate();
        // System.out.println(min);
        while (iter6.hasNext()) {

            Empleados emple = (Empleados) iter6.next();

            int EMPc = emple.getEmpNo();

            if (codEmpl == ultimo) {
                TFapellido.setText("No hay más empleados");
                TFoficio.setText("");
                TFdepartamento.setText("");
                TFsalario.setText("");
            } else if (EMPc == position) {
                TFnumero.setText(emple.getEmpNo() + "");
                TFapellido.setText(emple.getApellido() + "");
                TFoficio.setText(emple.getOficio() + "");
                TFdepartamento.setText(emple.getDepartamentos().getDnombre() + "");
                TFsalario.setText(emple.getSalario() + "");
            }
        }

          session.close();

    }//GEN-LAST:event_BTNsiguienteActionPerformed

    private void BTNanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNanteriorActionPerformed
       // •	El botón Anterior muestra el anterior empleado al que se está visualizando. Si se pulsa y estamos ante el primer empleado se debe visualizar un mensaje indicándolo (por ejemplo:” primer empleado”). Al hacer clic en el botón de cierre de la ventana finalizará el programa. 
        
        SessionFactory sesion = HibernateUtil.getSesionFactory();
        Session session = sesion.openSession();

        Query q7 = session.createQuery("from Empleados");

        q7.setFetchSize(10);
        Iterator iter7 = q7.iterate();

        ArrayList<Integer> listaEmp = new ArrayList<Integer>();

        while (iter7.hasNext()) {
            Empleados emple = (Empleados) iter7.next();
            int EMPc = emple.getEmpNo();
            listaEmp.add(EMPc);
        }

        //Posicion que tiene
        int codEmpl = Integer.valueOf(TFnumero.getText().toString());
        int position = 0;

        //Ultima posicion
        int primer = listaEmp.get(0);
        System.out.println("El primer numero empleado es: "+primer);

        
        if (codEmpl != primer) {
            for (int i = 0; i < listaEmp.size(); i++) {
                if (listaEmp.get(i) == codEmpl) {
                    position = listaEmp.get(i - 1);
                }
            }
        }

        Query q8 = session.createQuery("from Empleados");
        q8.setFetchSize(10);
        Iterator iter8 = q8.iterate();
        // System.out.println(min);
        while (iter8.hasNext()) {

            Empleados emple = (Empleados) iter8.next();

            int EMPc = emple.getEmpNo();

            if (codEmpl == primer) {
                TFapellido.setText("Es el primer empleado");
                TFoficio.setText("");
                TFdepartamento.setText("");
                TFsalario.setText("");
            } else if (EMPc == position) {
                TFnumero.setText(emple.getEmpNo() + "");
                TFapellido.setText(emple.getApellido() + "");
                TFoficio.setText(emple.getOficio() + "");
                TFdepartamento.setText(emple.getDepartamentos().getDnombre() + "");
                TFsalario.setText(emple.getSalario() + "");
            }
        }

          session.close();
    }//GEN-LAST:event_BTNanteriorActionPerformed

    private void BTNultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNultimoActionPerformed
        // TODO add your handling code here:
        SessionFactory sesion = HibernateUtil.getSesionFactory();
        Session session = sesion.openSession();

        Query q3 = session.createQuery("from Empleados");

        q3.setFetchSize(10);
        Iterator iter3 = q3.iterate();

        ArrayList<Integer> listaEmp = new ArrayList<Integer>();

        while (iter3.hasNext()) {
                Empleados emple = (Empleados) iter3.next();
                int EMPc = emple.getEmpNo();
                listaEmp.add(EMPc);
               // System.out.println(emple.getApellido() + ", " + emple.getEmpNo());   
        }
        

        int max = Collections.max(listaEmp);
        String res="";
        Query q4 = session.createQuery("from Empleados");
        q4.setFetchSize(10);
        Iterator iter4 = q4.iterate();
        // System.out.println(min);
        while(iter4.hasNext()){
             
            Empleados emple = (Empleados) iter4.next();
            int EMPc = emple.getEmpNo();
             if(EMPc==max){
                // System.out.println(emple.getApellido()+", "+emple.getEmpNo());
                 res = emple.getEmpNo()+"";
                 TFapellido.setText(emple.getApellido()+"");
                 TFoficio.setText(emple.getOficio()+"");
                 TFdepartamento.setText(emple.getDepartamentos().getDnombre()+"");
                 TFsalario.setText(emple.getSalario()+"");
                 //System.out.println(res);
             }  
       }
       
        TFnumero.setText(res);
        
         
        session.close();
    }//GEN-LAST:event_BTNultimoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         SessionFactory sesion = HibernateUtil.getSesionFactory();
        Session session = sesion.openSession();

        Query q9 = session.createQuery("from Empleados");

        q9.setFetchSize(10);
        Iterator iter9 = q9.iterate();

        ArrayList<Integer> listaEmp = new ArrayList<Integer>();

        while (iter9.hasNext()) {
                Empleados emple = (Empleados) iter9.next();
                int EMPc = emple.getEmpNo();
                listaEmp.add(EMPc);
        }
        

        int min = Collections.min(listaEmp);
        String res="";
        Query q10 = session.createQuery("from Empleados");
        q10.setFetchSize(10);
        Iterator iter10 = q10.iterate();
        // System.out.println(min);
        while(iter10.hasNext()){
             
            Empleados emple = (Empleados) iter10.next();
            int EMPc = emple.getEmpNo();
             if(EMPc==min){
                 
                 res = emple.getEmpNo()+"";
                 TFapellido.setText(emple.getApellido()+"");
                 TFoficio.setText(emple.getOficio()+"");
                 TFdepartamento.setText(emple.getDepartamentos().getDnombre()+"");
                 TFsalario.setText(emple.getSalario()+"");
                // System.out.println(res);
             }  
       }
       
        TFnumero.setText(res);
        
         
        session.close();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNanterior;
    private javax.swing.JButton BTNconsulta;
    private javax.swing.JButton BTNsiguiente;
    private javax.swing.JButton BTNultimo;
    private javax.swing.JTextField TFapellido;
    private javax.swing.JTextField TFdepartamento;
    private javax.swing.JTextField TFnumero;
    private javax.swing.JTextField TFoficio;
    private javax.swing.JTextField TFsalario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
